### ISSUE TITLE
Lattice Beams do not meet at corners every time

### ISSUE THREAD

**Issue by Niels-IO** [leap71/LEAP71_LatticeLibrary#1]
Hi there,

I was just playing with the LatticeLibraryShowCase.RegularTask example, and it seems that occasionally the LatticeBeams are not meeting up at a corner. 

<img width="309" alt="SCR-20231123-qnoo" src="https://github.com/leap71/LEAP71_LatticeLibrary/assets/47059882/a1f1a247-05fb-46a6-927a-9e345e1f6d4c">

Is this expected, or what could be the cause of this?

**Comment by josefinelissner** [comment]
Hi Niels!

They DO meet, but the lower beam reaches its maximum beam thickness before the corner of the cell. This is why it looks a bit off. It is an artifact that you only observe with the CellBasedBeamThickness. For the CellBasedBeamThickness I am averaging the cell's size and base my beam thickness gradient on that and if one corner is further away then the average size plus one sampling step, my TransFixed function overflows and starts from ratio 0 again (instead of limiting it to 1). So, in that particular case, you see this artifact because it is a over-proportionally long stretched cell corner...

I have just fixed it by limiting my ratio in the blue marked line below:
<img width="920" alt="Screenshot 2023-11-25 at 3 47 56 PM" src="https://github.com/leap71/LEAP71_LatticeLibrary/assets/44703282/baacdf2e-51dd-4a05-81f3-456066ed5947">

Let me know if you observe other faulty stuff like this. Great to see you testing it thoroughly!

**Comment by Niels-IO** [comment]
Hi Josefine,

Very nice! I am truly amazed how advanced this library is. Thanks for the quick fix!
